-- Существующая демонстрационная сущность сохраняется.
CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE products (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    article VARCHAR(255),
    barcode VARCHAR(255),
    price NUMERIC(38, 10),
    quantity NUMERIC(38, 10)
);
CREATE INDEX idx_products_article ON products (article);
