ALTER TABLE products ADD COLUMN description TEXT;
ALTER TABLE products ADD COLUMN supplier_article VARCHAR(255);
ALTER TABLE products ADD COLUMN brand VARCHAR(255);
ALTER TABLE products ADD COLUMN image TEXT;
ALTER TABLE products ADD COLUMN url TEXT;
ALTER TABLE products ADD COLUMN properties JSONB;
ALTER TABLE products ADD COLUMN offers JSONB;
ALTER TABLE products ADD COLUMN list_updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE products ADD COLUMN detail_updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE products ADD COLUMN detail_error VARCHAR(100);
CREATE TABLE stores (id BIGINT PRIMARY KEY, name TEXT);
CREATE TABLE product_stocks (
    product_id BIGINT NOT NULL REFERENCES products(id),
    store_id BIGINT NOT NULL REFERENCES stores(id),
    quantity NUMERIC(38,10),
    PRIMARY KEY (product_id, store_id)
);
CREATE TABLE catalog_sync_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(32) NOT NULL,
    reason VARCHAR(100),
    next_page INTEGER NOT NULL DEFAULT 1,
    list_complete BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE catalog_sync_pages (
    run_id BIGINT NOT NULL REFERENCES catalog_sync_runs(id),
    page INTEGER NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    PRIMARY KEY (run_id,page),
    UNIQUE (run_id,fingerprint)
);
CREATE TABLE catalog_sync_products (
    run_id BIGINT NOT NULL REFERENCES catalog_sync_runs(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    detail_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    error VARCHAR(100),
    PRIMARY KEY (run_id, product_id)
);
